// Comprehensive list of countries with ISO codes (sorted alphabetically by German name)
export const COUNTRIES = [
  { code: 'AD', name: 'Andorra' },
  { code: 'AE', name: 'Vereinigte Arabische Emirate' },
  { code: 'AR', name: 'Argentinien' },
  { code: 'AT', name: 'Österreich' },
  { code: 'AU', name: 'Australien' },
  { code: 'BE', name: 'Belgien' },
  { code: 'BG', name: 'Bulgarien' },
  { code: 'BR', name: 'Brasilien' },
  { code: 'CA', name: 'Kanada' },
  { code: 'CH', name: 'Schweiz' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CY', name: 'Zypern' },
  { code: 'CZ', name: 'Tschechien' },
  { code: 'DE', name: 'Deutschland' },
  { code: 'DK', name: 'Dänemark' },
  { code: 'EG', name: 'Ägypten' },
  { code: 'EE', name: 'Estland' },
  { code: 'ES', name: 'Spanien' },
  { code: 'FI', name: 'Finnland' },
  { code: 'FR', name: 'Frankreich' },
  { code: 'GB', name: 'Vereinigtes Königreich' },
  { code: 'GR', name: 'Griechenland' },
  { code: 'HR', name: 'Kroatien' },
  { code: 'HU', name: 'Ungarn' },
  { code: 'ID', name: 'Indonesien' },
  { code: 'IE', name: 'Irland' },
  { code: 'IL', name: 'Israel' },
  { code: 'IS', name: 'Island' },
  { code: 'IT', name: 'Italien' },
  { code: 'JP', name: 'Japan' },
  { code: 'KE', name: 'Kenia' },
  { code: 'KR', name: 'Südkorea' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Litauen' },
  { code: 'LU', name: 'Luxemburg' },
  { code: 'LV', name: 'Lettland' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MT', name: 'Malta' },
  { code: 'MX', name: 'Mexiko' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NL', name: 'Niederlande' },
  { code: 'NO', name: 'Norwegen' },
  { code: 'NZ', name: 'Neuseeland' },
  { code: 'PH', name: 'Philippinen' },
  { code: 'PL', name: 'Polen' },
  { code: 'PT', name: 'Portugal' },
  { code: 'RO', name: 'Rumänien' },
  { code: 'RU', name: 'Russland' },
  { code: 'SA', name: 'Saudi-Arabien' },
  { code: 'SE', name: 'Schweden' },
  { code: 'SG', name: 'Singapur' },
  { code: 'SI', name: 'Slowenien' },
  { code: 'SK', name: 'Slowakei' },
  { code: 'SM', name: 'San Marino' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TR', name: 'Türkei' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'US', name: 'Vereinigte Staaten' },
  { code: 'VA', name: 'Vatikanstadt' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'ZA', name: 'Südafrika' },
].sort((a, b) => a.name.localeCompare(b.name, 'de'))

